baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "MicroMDM"
metadataformat = "yaml"
theme = "hugo-material-docs"
canonifyurls = true

[params]
	# General information
	description = "An open source MDM server for OS X"
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/micromdm/micromdm"

	version = "0.1.0-alpha"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "light green"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

[[menu.main]]
	name   = "MicroMDM"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name   = "Management API"
	url    = "management-api/"
	weight = 20

[blackfriday]
smartypants	= true
fractions = true
smartDashes = true
plainIDAnchors = true
